services:
    backend:
        build: .
        ports:
            - '3002:3002'

    db:
        image: postgres:latest
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: mydb
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
